whatwg/mimesniff

Overview.html, Overview.src.html
Fix https://www.w3.org/Bugs/Public/show_bug.cgi?id=29243.
=> Parsing-a-mime-type do not check for the condition if sequence[s] is undefined

Overview.html, Overview.src.html
- Reverse the failures condition in `match mp3 header`.
- The sample-rate index is at index 2 and not 3.
- Compute the `freq` variable.
- Fix the index in the sample-rate table.
- Add the second operand to the right bit shift when computing the layer.
This fixes #11.
=> Fix mp3 parse

mimesniff.bs
Since commit https://github.com/whatwg/mimesniff/commit/998b959332e8dd372f06cfde23f48b4ed5e3567c has changed the required buffer size to 1445,
it might be reasonable to change the read limitation to 1445 too.
***
[Preview](https://s3.amazonaws.com/pr-preview/spacewander/mimesniff/update_max_size.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/mimesniff/c8d435f...spacewander:9e04b40.html)
=> Update the read limitation to 1445

mimesniff.bs
TODO:
***
<a href="https://whatpr.org/mimesniff/36.html" title="Last updated on Dec 4, 2017, 12:08 PM GMT (3f70580)">Preview</a> | <a href="https://whatpr.org/mimesniff/36/74065de...3f70580.html" title="Last updated on Dec 4, 2017, 12:08 PM GMT (3f70580)">Diff</a>
=> Revamp MIME type section

mimesniff.bs
* Closes #27: updates the font sniffing algorithm to give the correct computed MIME types
* Closes #23: counts font/* MIME types as font types, and uses the canonical names for the computed MIME types when sniffing fonts specifically
* Closes #28: adds the ability to sniff WOFF 2 resources
/cc participants in those threads: @bradleyfalzon @LeoColomb @svgeesus.
There's a separate issue of whether browsers do MIME sniffing for fonts at all, as @annevk has alluded to, but the spec at least seems to imply that they do, so let's make it accurate for now.
***
<a href="https://whatpr.org/mimesniff/57.html" title="Last updated on Feb 5, 2018, 9:37 PM GMT (5d29af7)">Preview</a> | <a href="https://whatpr.org/mimesniff/57/4227e12...5d29af7.html" title="Last updated on Feb 5, 2018, 9:37 PM GMT …
=> Update font types list and sniffing

mimesniff.bs
Notably, this ensures that the terms always say "MIME type", instead of sometimes "type" and sometimes "MIME type". It also tidies up some of the essence lists.
---
This does not touch the font type definition, since #27 fixes that in similar ways.
***
<a href="https://whatpr.org/mimesniff/59.html" title="Last updated on Feb 9, 2018, 6:13 PM GMT (ed9de51)">Preview</a> | <a href="https://whatpr.org/mimesniff/59/e29b9f4...ed9de51.html" title="Last updated on Feb 9, 2018, 6:13 PM GMT (ed9de51)">Diff</a>
=> Editorial: tweak MIME type group definitions

mimesniff.bs
This consolidates the lists of MIME types in a single specification, instead of spreading them out among two.
Followup HTML PR incoming.
***
<a href="https://whatpr.org/mimesniff/58.html" title="Last updated on Feb 9, 2018, 3:25 PM GMT (551ce13)">Preview</a> | <a href="https://whatpr.org/mimesniff/58/e29b9f4...551ce13.html" title="Last updated on Feb 9, 2018, 3:25 PM GMT (551ce13)">Diff</a>
=> Move JavaScript and JSON MIME types from HTML

mimesniff.bs
See https://github.com/triple-underscore/triple-underscore.github.io/issues/1#issuecomment-368372481.
***
<a href="https://whatpr.org/mimesniff/62.html" title="Last updated on Feb 26, 2018, 7:41 AM GMT (2c191fd)">Preview</a> | <a href="https://whatpr.org/mimesniff/62/2ca219f...2c191fd.html" title="Last updated on Feb 26, 2018, 7:41 AM GMT (2c191fd)">Diff</a>
=> Link Japanese translation

mimesniff.bs
HTML uses "computed mime type", and I'd like to use "supplied" in a new
spec.
***
<a href="https://whatpr.org/mimesniff/75.html" title="Last updated on Jul 25, 2018, 9:28 PM GMT (3af69d5)">Preview</a> | <a href="https://whatpr.org/mimesniff/75/0d26018...3af69d5.html" title="Last updated on Jul 25, 2018, 9:28 PM GMT (3af69d5)">Diff</a>
=> Export the supplied and computed mime type dfns.

mimesniff.bs
I think this was meant.
***
<a href="https://whatpr.org/mimesniff/83.html" title="Last updated on Oct 4, 2018, 8:33 AM GMT (3ff10b2)">Preview</a> | <a href="https://whatpr.org/mimesniff/83/190c18a...3ff10b2.html" title="Last updated on Oct 4, 2018, 8:33 AM GMT (3ff10b2)">Diff</a>
=> Indicate correct unicode

mimesniff.bs
Tests: https://github.com/web-platform-tests/wpt/pull/13615.
Fixes #89.
***
<a href="https://whatpr.org/mimesniff/90.html" title="Last updated on Oct 30, 2018, 1:11 PM GMT (7a80894)">Preview</a> | <a href="https://whatpr.org/mimesniff/90/dc35803...7a80894.html" title="Last updated on Oct 30, 2018, 1:11 PM GMT (7a80894)">Diff</a>
=> Use HTTP rather than ASCII whitespace

mimesniff.bs
See https://github.com/whatwg/fetch/pull/831.
***
<a href="https://whatpr.org/mimesniff/92.html" title="Last updated on Nov 22, 2018, 8:53 AM GMT (de107ef)">Preview</a> | <a href="https://whatpr.org/mimesniff/92/126286a...de107ef.html" title="Last updated on Nov 22, 2018, 8:53 AM GMT (de107ef)">Diff</a>
=> Use collect an HTTP quoted string

mimesniff.bs
All bugs have been moved to GitHub.
***
<a href="https://whatpr.org/mimesniff/103.html" title="Last updated on Mar 30, 2019, 10:16 PM UTC (31375ad)">Preview</a> | <a href="https://whatpr.org/mimesniff/103/5aa48d4...31375ad.html" title="Last updated on Mar 30, 2019, 10:16 PM UTC (31375ad)">Diff</a>
=> Meta: remove "Legacy open bugs" link

mimesniff.bs
Fixes #141.
***
<a href="https://whatpr.org/mimesniff/142.html" title="Last updated on Apr 26, 2021, 10:36 AM UTC (cf120dc)">Preview</a> | <a href="https://whatpr.org/mimesniff/142/609a3a3...cf120dc.html" title="Last updated on Apr 26, 2021, 10:36 AM UTC (cf120dc)">Diff</a>
=> MIME type parameters can hold non-ASCII code points

mimesniff.bs
Fixes #151. Reverts dd50d72888f9cbfbd4998c61488e961628d1c87b.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/mimesniff/153.html" title="Last updated on Sep 4, 2021, 12:00 AM UTC (a22d538)">Preview</a> | <a href="https://whatpr.org/mimesniff/153/dee1ee9...a22d538.html" title="Last updated on Sep 4, 2021, 12:00 AM UTC (a22d538)">Diff</a>
=> Remove basic audio signature

mimesniff.bs
Update the usage of "collect an HTTP quoted string" in the "parse a MIME type" algorithm following changes to the algorithm's input.
Related to: whatwg/fetch#1567
***
<a href="https://whatpr.org/mimesniff/170.html" title="Last updated on Apr 25, 2023, 1:25 AM UTC (a4d11fc)">Preview</a> | <a href="https://whatpr.org/mimesniff/170/e589fcb...a4d11fc.html" title="Last updated on Apr 25, 2023, 1:25 AM UTC (a4d11fc)">Diff</a>
=> Editorial: Update parse a MIME type

mimesniff.bs
All the ABNF moved over to HTTP Semantics, and the one remaining reference to HTTP-1.1 didn't seem specific to that version, so I removed the HTTP-1.1 reference.
I believe this is entirely editorial.
***
<a href="https://whatpr.org/mimesniff/182.html" title="Last updated on Dec 11, 2023, 6:55 PM UTC (6ff8bc8)">Preview</a> | <a href="https://whatpr.org/mimesniff/182/26d790b...6ff8bc8.html" title="Last updated on Dec 11, 2023, 6:55 PM UTC (6ff8bc8)">Diff</a>
=> Editorial: Update the references to the HTTP RFCs.

mimesniff.bs
(fixes #184)
* No need for new tests, the wpt already use the proper algorithm.
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/mimesniff/186.html" title="Last updated on Mar 19, 2024, 12:01 AM UTC (c3b7103)">Preview</a> | <a href="https://whatpr.org/mimesniff/186/fe4647d...c3b7103.html" title="Last updated on Mar 19, 2024, 12:01 AM UTC (c3b7103)">Diff</a>
=> Fix off-by-one loop index

mimesniff.bs
Correct inverted test logic to determine if we've reached the end of the EBML element.
(fixes #185)
***
<a href="https://whatpr.org/mimesniff/187.html" title="Last updated on Mar 25, 2024, 1:18 PM UTC (42541da)">Preview</a> | <a href="https://whatpr.org/mimesniff/187/fe4647d...42541da.html" title="Last updated on Mar 25, 2024, 1:18 PM UTC (42541da)">Diff</a>
=> Signature for WebM will always return false

mimesniff.bs
I'd like to reference them in https://github.com/whatwg/fetch/pull/1755, hence this patch to export those two algorithms.
* This is an editorial thing, I don't think implementers interests are needed 
* Also not needed
* Also not needed
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/mimesniff/190.html" title="Last updated on Jun 11, 2024, 2:19 PM UTC (ade7608)">Preview</a> | <a href="https://whatpr.org/mimesniff/190/60ebda1...ade7608.html" title="Last updated on Jun 11, 2024, 2:19 PM UTC (ade7608)">Diff</a>
=> Export the image pattern and the media pattern algorithm

mimesniff.bs
As no user agent today appears to identify a text/html resource starting with <rss as XML, remove those rules from the standard.
At the same time, make it more clear that XML (and now HTML) are never sniffed. This is a non-normative change for clarity.
Tests: https://github.com/web-platform-tests/wpt/pull/47002.
Closes #173.
* WebKit
* Presumably Chromium and Gecko as they don't implement this
* https://github.com/web-platform-tests/wpt/pull/47002
* Chromium: N/A
* Gecko: N/A
* WebKit: N/A
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/mimesniff/192.html" title="Last updated on Jul 4, 2024, 12:36 PM UTC (f23deaa)">Preview</a> | <a href="https://whatpr.org/mimesniff/192/3624957...f23deaa.html" title="Last …
=> Remove sniffing of HTML

mimesniff.bs
Fixes #197.
***
<a href="https://whatpr.org/mimesniff/198.html" title="Last updated on May 19, 2025, 10:50 AM UTC (8c1d889)">Preview</a> | <a href="https://whatpr.org/mimesniff/198/e1d3838...8c1d889.html" title="Last updated on May 19, 2025, 10:50 AM UTC (8c1d889)">Diff</a>
=> Vint algorithm: Move index initialization to before mask loop
